# Generated by Django 4.0.2 on 2022-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_type', models.CharField(max_length=255)),
                ('battery_capacity', models.CharField(max_length=255)),
                ('stand_by_time', models.CharField(max_length=255)),
                ('talktime', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Battery',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_height', models.CharField(max_length=255)),
                ('body_width', models.CharField(max_length=255)),
                ('body_thickness', models.CharField(max_length=255)),
                ('body_weight', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Body',
                'verbose_name_plural': 'Body',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear_camera', models.TextField()),
                ('rear_camera_flash', models.BooleanField(default=True)),
                ('front_camera', models.TextField()),
                ('front_camera_flash', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camera',
            },
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=True)),
                ('radio', models.BooleanField(default=True)),
                ('infrared', models.BooleanField(default=True)),
                ('gprs', models.BooleanField(default=True)),
                ('edge', models.BooleanField(default=True)),
                ('nfc', models.BooleanField(default=True)),
                ('usb', models.BooleanField(default=True)),
                ('bluetooth_version', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Connectivity',
                'verbose_name_plural': 'Connectivity',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=255)),
                ('screen_resolution', models.CharField(max_length=255)),
                ('display_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Display',
                'verbose_name_plural': 'Display',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField()),
                ('sim_type', models.CharField(choices=[('Micro-Sim', 'Micro-Sim'), ('Nano-Sim', 'Nano-Sim')], default='Micro-Sim', max_length=10)),
                ('dual_sim', models.BooleanField(default=True)),
                ('touch_screen', models.BooleanField(default=True)),
                ('fingerprint_unlock', models.BooleanField(default=True)),
                ('face_lock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'General',
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_memory', models.IntegerField()),
                ('external_memory', models.IntegerField()),
                ('ram', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memory',
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': 'OS',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(max_length=255)),
                ('processor_speed', models.CharField(max_length=255)),
                ('chipset_group', models.CharField(max_length=255)),
                ('chipset_details', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Processor',
                'verbose_name_plural': 'Processor',
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jack_35mm', models.BooleanField(default=True)),
                ('loudspeaker', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sound',
                'verbose_name_plural': 'Sound',
            },
        ),
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear_camera_video_quality', models.TextField()),
            ],
            options={
                'verbose_name': 'VideoRecording',
                'verbose_name_plural': 'VideoRecording',
            },
        ),
    ]
