# Generated by Django 4.0.2 on 2022-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='bluetooth_version',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='general',
            name='sim_type',
            field=models.CharField(choices=[('Nano-Sim', 'Nano-Sim'), ('Micro-Sim', 'Micro-Sim')], default='Micro-Sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='memory',
            name='external_memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='internal_memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='ram',
            field=models.FloatField(),
        ),
    ]
