# Generated by Django 4.0.2 on 2022-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_connectivity_bluetooth_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='sim_type',
            field=models.CharField(choices=[('Micro-Sim', 'Micro-Sim'), ('Nano-Sim', 'Nano-Sim')], default='Micro-Sim', max_length=10),
        ),
    ]
