# Generated by Django 4.0.2 on 2022-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_general_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='stand_by_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='talktime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='body_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='front_camera',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rear_camera',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='bluetooth_version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='general',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memory',
            name='external_memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorecording',
            name='rear_camera_video_quality',
            field=models.CharField(max_length=255),
        ),
    ]
