# Generated by Django 4.0.2 on 2022-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_battery_stand_by_time_alter_battery_talktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='sim_type',
            field=models.CharField(choices=[('Nano-Sim', 'Nano-Sim'), ('Micro-Sim', 'Micro-Sim')], default='Micro-Sim', max_length=10),
        ),
    ]
