# Generated by Django 4.0.3 on 2022-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_alter_general_sim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='sim_type',
            field=models.CharField(choices=[('Nano-Sim', 'Nano-Sim'), ('Micro-Sim', 'Micro-Sim')], default='Micro-Sim', max_length=10),
        ),
    ]
