# Generated by Django 4.0.1 on 2022-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('long_decription', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('image', models.URLField()),
                ('brand', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('stock', models.IntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(related_name='products', to='flipkart.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
