# Generated by Django 4.0.2 on 2022-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0004_availability_mobile_specification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Availability', 'verbose_name_plural': 'Availability'},
        ),
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'Mobile', 'verbose_name_plural': 'Mobiles'},
        ),
        migrations.AlterField(
            model_name='availability',
            name='upcoming_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
