# Generated by Django 4.0.2 on 2022-02-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productimage', '0001_initial'),
        ('mobile', '0005_alter_general_sim_type'),
        ('flipkart', '0005_alter_availability_options_alter_mobile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_mobile', to='flipkart.availability'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_mobile', to='flipkart.brand'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_mobile', to='productimage.productimage'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='specifications',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_mobile', to='flipkart.specification'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_mobile', to='flipkart.vendor'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.battery'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.body'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.camera'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='connectivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.connectivity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.display'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.general'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.memory'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.os'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.processor'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.sound'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='video_recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart_specification', to='mobile.videorecording'),
        ),
    ]
